version: '2'
services:
  app:
    image: budget_service
    command: bash -c "bundle && RAILS_ENV=development bundle exec rake db:drop db:create db:migrate db:seed && RAILS_ENV=development bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: budget_app
    tty: true
    stdin_open: true
    environment:
      - DOCKER_DB_HOST=my_postgres
    volumes:
      - ../budget:/budget
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    networks:
      default:
        aliases:
          - dev.budget.com
  # db:
  #   image: library/mysql:5.6.22
  #   container_name: budget_db
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=admin
  #     - MYSQL_DATABASE=dev_budget_db
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=admin

  db:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
